name: "Check Exact Files Changed"
description: "Check Exact Files Changed"
author: "fforres"

inputs:
  file-patterns:
    description: "An array of patterns that represent the files that should be included in the PR."
    required: false
    default: "1"

  comparison-mode:
    description: "The way we are checking if files where modified. Options: 'exact' or 'contains'"
    required: false
    default: "exact"

  fail-mode:
    description: "If the action will trigger a flow error, or it will allow going. Options: 'hard' or 'soft'"
    required: false
    default: "soft"

  token:
    description: "The GitHub token used to create an authenticated client."
    required: true

outputs:
  success:
    description: "The success of the validated files."

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "green"
