on: push

jobs:
  default:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./ #uses local latest version for testing purposes
        with:
          file-patterns: '["package.json"]'
          token: ${{ secrets.GITHUB_TOKEN }}

  comparisonMode:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./ #uses local latest version for testing purposes
        with:
          file-patterns: '["package.json"]'
          comparison-mode: "exact"
          token: ${{ secrets.GITHUB_TOKEN }}

  failMode:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./ #uses local latest version for testing purposes
        with:
          file-patterns: '["package.json"]'
          comparison-mode: "soft"
          token: ${{ secrets.GITHUB_TOKEN }}
